/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function PhoneMan({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model3d/BaseCharacter_phone.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Bone} />
      <skinnedMesh geometry={nodes.Cube004.geometry} skeleton={nodes.Cube004.skeleton} > <meshStandardMaterial color={'#FFB900'} /> </skinnedMesh>
      <skinnedMesh geometry={nodes.Cube004_1.geometry} skeleton={nodes.Cube004_1.skeleton} > </skinnedMesh>
      <mesh geometry={nodes.Cube.geometry} position={[0, 1.6, 0.74]} rotation={[0.4, 0, 0]} scale={[0.22, 0.12, 0.04]} > <meshStandardMaterial color={'#7B68EE'} /> </mesh>
    </group>
  )
}

useGLTF.preload('/model3d/BaseCharacter_phone.glb')
