/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function AngryMan({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model3d/BaseCharacter.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Bone} />
      <skinnedMesh geometry={nodes.Cube004.geometry} skeleton={nodes.Cube004.skeleton} > <meshStandardMaterial color={'#FFB900'} /> </skinnedMesh>
      <skinnedMesh geometry={nodes.Cube004_1.geometry} material={materials.Face} skeleton={nodes.Cube004_1.skeleton} />
    </group>
  )
}

useGLTF.preload('/model3d/BaseCharacter.glb')
