/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF  } from '@react-three/drei'
import {  useFrame } from '@react-three/fiber'

export default function Mrviz_logo({ ...props }) {
  const group = useRef()
  const offset = Math.random() * 10
  const { nodes, materials } = useGLTF('/model3d/mrviz_logo.glb')
  useFrame((state) => {
    const t = state.clock.getElapsedTime() + offset 
    group.current.rotation.x = group.current.rotation.x + Math.sin(t)/(1000)
    group.current.rotation.y = group.current.rotation.y + Math.sin(t)/1000
    group.current.rotation.z = group.current.rotation.z + Math.cos(t)/1000
    group.current.position.y = group.current.position.y + (Math.sin(t))/1000
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.X_axis.geometry} material-color="#F25022" />
      <mesh geometry={nodes.Y_axis.geometry} material-color="#7FBA00" rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Z_axis.geometry} material-color="#00A4EF" rotation={[0, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/model3d/mrviz_logo.glb')
